ALTER TABLE books
  ADD COLUMN price DECIMAL(10,2) NULL AFTER description,
  ADD COLUMN currency VARCHAR(6) NOT NULL DEFAULT 'SAR' AFTER price,
  ADD COLUMN rating DECIMAL(2,1) NULL AFTER currency,
  ADD COLUMN reviews_count INT UNSIGNED NOT NULL DEFAULT 0 AFTER rating;

CREATE TABLE IF NOT EXISTS book_external_links (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  book_id INT UNSIGNED NOT NULL,
  label VARCHAR(100) NOT NULL,
  url VARCHAR(255) NOT NULL,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_book_external_links_book FOREIGN KEY (book_id) REFERENCES books (id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
